name: Validate

on: push

jobs:
  validate:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: install deps
      run: |
        gem install mustache
        sudo curl -Lo /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        sudo chmod +x /usr/local/bin/jq
        sudo curl -Lo /usr/local/bin/coursier https://git.io/coursier-cli
        sudo chmod +x /usr/local/bin/coursier
    - name: build site
      run: |
        ./bin/build-talks.sh
        sbt 'docs/docusaurusCreateSite'
      env:
        CI: true
